export const COINS = {
  BTC: 'BTC',
  ETH: 'ETH',
  USDT: 'USDT',
  BNB: 'BNB',
  SOL: 'SOL',
  USDC: 'USDC',
  XRP: 'XRP',
  TON: 'TON',
  DOGE: 'DOGE',
  ADA: 'ADA',
  TRX: 'TRX',
  AVAX: 'AVAX',
  SHIB: 'SHIB',
  DOT: 'DOT',
  LINK: 'LINK',
  BCH: 'BCH',
  DAI: 'DAI',
  LTC: 'LTC',
  MATIC: 'MATIC',
  UNI: 'UNI',
  PEPE: 'PEPE',
  FIL: 'FIL',
  ARB: 'ARB',
  OP: 'OP',
  FDUSD: 'FDUSD',
  WIF: 'WIF',
  NOT: 'NOT',
  BONK: 'BONK',
  AAVE: 'AAVE',
  BGB: 'BGB',
  FLOKI: 'FLOKI',
  JUP: 'JUP',
  CORE: 'CORE',
  ENS: 'ENS',
  W: 'W',
  SATS: 'SATS',
  CRV: 'CRV',
  PEOPLE: 'PEOPLE',
  NEW: 'MEW',
  ETHFI: 'ETHFI',
  BUSD: 'BUSD',
  WBTC: "WBTC",
  WETH: "WETH"
};

export const STABLE_COINS = [COINS.USDT, COINS.USDC, COINS.BUSD, COINS.FDUSD];
